Feature:
  # param
  object_feature_type: ""  # "ade20k"
  angle_feat_size: 4
  max_objects: 70
  # feature
  image_feat_size: 1024
  feature_database:
    "mp3d": "eva_features/mp3d_EVA02-CLIP-L-14-336.hdf5"
    "scan_qa": "eva_features/scanqa_EVA02-CLIP-L-14-336.hdf5"
    "coco": "eva_features/coco_EVA02-CLIP-L-14-336.hdf5"

  # object
  obj_feat_size: 768
  object_database:
    "reverie": "obj_features/reverie_obj_feat"
    "soon": "obj_features/soon_obj_feat"

# task
Dataset:
  R2R:
    DIR: "R2R"
    SPLIT: {
      "train": "FGR2R_train.json",
      "val_seen": "R2R_val_seen_enc.json",
      "val_unseen": "R2R_val_unseen_enc.json",
      "test": "R2R_test_enc.json"
    }
  REVERIE:
    DIR: "REVERIE"
    bbox_file: "BBoxes.json"
    SPLIT: {
      "train": "REVERIE_train_enc.json",
      "val_seen": "REVERIE_val_seen_enc.json",
      "val_unseen": "REVERIE_val_unseen_enc.json",
      "test": "REVERIE_test_enc.json"
    }
  CVDN:
    DIR: "CVDN"
    SPLIT: {
      "train": "train.json",
      "val_seen": "val_seen.json",
      "val_unseen": "val_unseen.json",
      "test": "test_cleaned.json"
    }
  SOON:
    DIR: "SOON"  # from https://github.com/cshizhe/HM3DAutoVLN
    SPLIT: {
      "train": "train_enc_pseudo_obj_ade30k_label.jsonl",
      "val_seen": "val_unseen_instrs_enc_pseudo_obj_ade30k_label.jsonl",
      "val_unseen": "val_unseen_house_enc_pseudo_obj_ade30k_label.jsonl",
      "test": "test_v2_enc.jsonl"
    }
  ScanQA:
    DIR: "ScanQA"
    SPLIT: {
      "train": "ScanQA_v1.0_train_reformat.json",
      "val_unseen": "ScanQA_v1.0_val_reformat.json",
      "test_wo_obj": "ScanQA_v1.0_test_wo_obj_reformat.json",
      "test_w_obj": "ScanQA_v1.0_test_w_obj_reformat.json"
    }
  EQA:
    DIR: "EQA_MP3D"
    SPLIT: {
      "val_unseen": "eqa_val_enc.json"
    }
    ANSWER_VOCAB: "eqa_answer_vocab.json"
  
  R2R_AUG:
    DIR: "R2R"
    SPLIT: {
      "train": "R2R_prevalent_aug_train_enc.jsonl"
    }
  REVERIE_AUG:
    DIR: "REVERIE"
    bbox_file: "BBoxes.json"
    SPLIT: {
      "train": "REVERIE_speaker_aug_enc.jsonl"
    }
  LLaVA:
    DIR: "LLaVA"
    SPLIT: {
      "train": "detail_23k.json"
    }

# training
Pretrain:
  SOURCE: ['R2R_AUG', 'REVERIE_AUG', 'R2R', 'REVERIE', 'SOON', 'CVDN', 'ScanQA']
  Ratio: [20, 2, 1, 1, 1, 1, 1]
  LOSS_COEF: {
    "R2R_AUG": 1,
    "REVERIE_AUG": 1
  }


Multi:
  SOURCE: ['R2R', 'REVERIE', 'CVDN','SOON', 'ScanQA', 'LLaVA']
  Ratio: [20, 5, 1, 5, 5, 5]
  LOSS_COEF: {
  }


Model:
  num_l_layers: 9
  num_pano_layers: 2
  num_x_layers: 4
  graph_sprels: True
  fusion: "dynamic"
  enc_full_graph: True
  expert_policy: "spl"

Optim:
  val_max_action_len: {
    "R2R": 15,
    "REVERIE": 15,
    "CVDN": 30, # from VLN-SIG
    "SOON": 20, # from DUET
    "EQA": 15,
  }
  train_max_action_len: {
    "R2R": 15,
    "REVERIE": 15,
    "CVDN": 15,
    "SOON": 15,
    "EQA": 15,
    "R2R_AUG": 15,
    "REVERIE_AUG": 15
  }